# see roles/network_plugin/cilium/defaults/main.yml

# Overlay Network Mode
cilium_tunnel_mode: vxlan
# Optional features
cilium_enable_prometheus: false
# Enable if you want to make use of hostPort mappings
cilium_enable_portmap: false
# Kube Proxy Replacement mode (strict/probe/partial)
cilium_kube_proxy_replacement: strict