all:
  hosts:
    node1:
      ansible_host: 172.36.100.16
      ip: 172.36.100.16
      access_ip: 172.36.100.16
    node2:
      ansible_host: 172.36.100.17
      ip: 172.36.100.17
      access_ip: 172.36.100.17
    node3:
      ansible_host: 172.36.100.18
      ip: 172.36.100.18
      access_ip: 172.36.100.18
    node4:
      ansible_host: 172.36.100.19
      ip: 172.36.100.19
      access_ip: 172.36.100.19
    node5:
      ansible_host: 172.36.100.20
      ip: 172.36.100.20
      access_ip: 172.36.100.20
    node6:
      ansible_host: 172.36.100.21
      ip: 172.36.100.21
      access_ip: 172.36.100.21
  children:
    kube-master:
      hosts:
        node1:
        node2:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
        node6:
      vars:
        ansible_user: haruband
        ansible_become: yes
        ansible_sudo_pass: kk3249
        metallb_ip_range:
          - "172.36.100.212-172.36.100.213"
        metallb_protocol: "layer2"
    etcd:
      hosts:
        node1:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}