all:
  hosts:
    node1:
      ip: 10.2.1.2
      ansible_host: 10.2.1.2
      access_ip: 10.2.1.2
    node2:
      ip: 10.2.1.3
      ansible_host: 10.2.1.3
      access_ip: 10.2.1.3
    node3:
      ip: 10.2.1.4
      ansible_host: 10.2.1.4
      access_ip: 10.2.1.4
  children:
    kube-master:
      hosts:
        node1:
        node2:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
      vars:
        ansible_user: haruband
        ansible_sudo_pass: kk3249
        ansible_become: yes
        metallb_enabled: false
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
