all:
  hosts:
    node1:
      ip: 10.2.1.13
      ansible_host: 10.2.1.13
      access_ip: 10.2.1.13
    node2:
      ip: 10.2.1.12
      ansible_host: 10.2.1.12
      access_ip: 10.2.1.12
    node3:
      ip: 10.2.1.11
      ansible_host: 10.2.1.11
      access_ip: 10.2.1.11
  children:
    kube-master:
      hosts:
        node1:
        node2:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
      vars:
        ansible_user: haruband
        ansible_sudo_pass: kk3249
        ansible_become: yes
        cilium_datapath_mode: "ipvlan"
        cilium_ipvlan_master: ens35
        metallb_enabled: false
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
