all:
  hosts:
    node1:
      ip: 20.0.0.245
      ansible_host: 20.0.0.245
      access_ip: 20.0.0.245
    node2:
      ip: 20.0.0.189
      ansible_host: 20.0.0.189
      access_ip: 20.0.0.189
    node3:
      ip: 20.0.0.158
      ansible_host: 20.0.0.158
      access_ip: 20.0.0.158
  children:
    kube-master:
      hosts:
        node1:
        node2:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
      vars:
        ansible_user: root
        ansible_sudo_pass: kk3249
        ansible_become: yes
        metallb_enabled: false
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
