all:
  hosts:
    node1:
      ansible_host: 172.26.50.106
      ip: 172.26.50.106
      access_ip: 172.26.50.106
    node2:
      ansible_host: 172.26.50.107
      ip: 172.26.50.107
      access_ip: 172.26.50.107
    node3:
      ansible_host: 172.26.50.108
      ip: 172.26.50.108
      access_ip: 172.26.50.108
    node4:
      ansible_host: 172.26.50.109
      ip: 172.26.50.109
      access_ip: 172.26.50.109
    node5:
      ansible_host: 172.26.50.110
      ip: 172.26.50.110
      access_ip: 172.26.50.110
    node6:
      ansible_host: 172.26.50.111
      ip: 172.26.50.111
      access_ip: 172.26.50.111
  children:
    kube-master:
      hosts:
        node1:
        node2:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
        node6:
      vars:
        ansible_user: haruband
        ansible_become: yes
        ansible_sudo_pass: kk3249
        metallb_ip_range:
          - "172.26.50.246-172.26.50.247"
        metallb_protocol: "layer2"
    etcd:
      hosts:
        node1:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}