all:
  hosts:
    node1:
      ansible_host: 192.168.6.32
      ip: 192.168.6.32
      access_ip: 192.168.6.32
    node2:
      ansible_host: 192.168.6.33
      ip: 192.168.6.33
      access_ip: 192.168.6.33
    node3:
      ansible_host: 192.168.6.193
      ip: 192.168.6.193
      access_ip: 192.168.6.193
    node4:
      ansible_host: 192.168.6.35
      ip: 192.168.6.35
      access_ip: 192.168.6.35
    node5:
      ansible_host: 192.168.6.36
      ip: 192.168.6.36
      access_ip: 192.168.6.36
  children:
    kube-master:
      hosts:
        node1:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
      vars:
        ansible_user: haruband
        ansible_become: yes
        ansible_sudo_pass: kk3249
        metallb_ip_range:
          - "192.168.6.244-192.168.6.245"
        metallb_protocol: "layer2"
    etcd:
      hosts:
        node1:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
